// Date: 23/02/2015 16:56:54
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package yam.blocks.model;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelLaunchPad extends ModelBase
{
  //fields
    ModelRenderer base;
    ModelRenderer platform;
    ModelRenderer pole1;
    ModelRenderer pole2;
    ModelRenderer pole3;
    ModelRenderer pole4;
  
  public ModelLaunchPad()
  {
    textureWidth = 64;
    textureHeight = 32;
    
      base = new ModelRenderer(this, 0, 0);
      base.addBox(-5F, -1F, -5F, 10, 1, 10);
      base.setRotationPoint(0F, 24F, 0F);
      base.setTextureSize(64, 32);
      base.mirror = true;
      setRotation(base, 0F, 0F, 0F);
      platform = new ModelRenderer(this, 0, 11);
      platform.addBox(-3.5F, -1.2F, -3.5F, 7, 1, 7);
      platform.setRotationPoint(0F, 24F, 0F);
      platform.setTextureSize(64, 32);
      platform.mirror = true;
      setRotation(platform, 0F, 0F, 0F);
      pole1 = new ModelRenderer(this, 40, 0);
      pole1.addBox(-5F, -24F, 4F, 1, 23, 1);
      pole1.setRotationPoint(0F, 24F, 0F);
      pole1.setTextureSize(64, 32);
      pole1.mirror = true;
      setRotation(pole1, 0F, 0F, 0F);
      pole2 = new ModelRenderer(this, 40, 0);
      pole2.addBox(4F, -24F, 4F, 1, 23, 1);
      pole2.setRotationPoint(0F, 24F, 0F);
      pole2.setTextureSize(64, 32);
      pole2.mirror = true;
      setRotation(pole2, 0F, 0F, 0F);
      pole3 = new ModelRenderer(this, 40, 0);
      pole3.addBox(-5F, -24F, -5F, 1, 23, 1);
      pole3.setRotationPoint(0F, 24F, 0F);
      pole3.setTextureSize(64, 32);
      pole3.mirror = true;
      setRotation(pole3, 0F, 0F, 0F);
      pole4 = new ModelRenderer(this, 40, 0);
      pole4.addBox(4F, -24F, -5F, 1, 23, 1);
      pole4.setRotationPoint(0F, 24F, 0F);
      pole4.setTextureSize(64, 32);
      pole4.mirror = true;
      setRotation(pole4, 0F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    base.render(f5);
    platform.render(f5);
    pole1.render(f5);
    pole2.render(f5);
    pole3.render(f5);
    pole4.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity e)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5, null);
  }

}
