// Date: 01/3/2015 2:48:15 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package net.minecraft.src;

public class ModelModel extends ModelBase
{
  //fields
    ModelRenderer core;
    ModelRenderer base;
    ModelRenderer head1;
    ModelRenderer head2;
    ModelRenderer divider;
  
  public ModelModel()
  {
    textureWidth = 64;
    textureHeight = 64;
    
      core = new ModelRenderer(this, 0, 32);
      core.addBox(-7F, -15F, -7F, 14, 14, 14);
      core.setRotationPoint(0F, 24F, 0F);
      core.setTextureSize(64, 64);
      core.mirror = true;
      setRotation(core, 0F, 0F, 0F);
      base = new ModelRenderer(this, 0, 0);
      base.addBox(-8F, -4F, -8F, 16, 4, 16);
      base.setRotationPoint(0F, 24F, 0F);
      base.setTextureSize(64, 64);
      base.mirror = true;
      setRotation(base, 0F, 0F, 0F);
      head1 = new ModelRenderer(this, 0, 0);
      head1.addBox(0F, 0F, 0F, 5, 10, 16);
      head1.setRotationPoint(-8F, 8F, -8F);
      head1.setTextureSize(64, 64);
      head1.mirror = true;
      setRotation(head1, 0F, 0F, 0F);
      head2 = new ModelRenderer(this, 0, 0);
      head2.addBox(0F, 0F, 0F, 7, 10, 16);
      head2.setRotationPoint(1F, 8F, -8F);
      head2.setTextureSize(64, 64);
      head2.mirror = true;
      setRotation(head2, 0F, 0F, 0F);
      divider = new ModelRenderer(this, 0, 0);
      divider.addBox(0F, 0F, 0F, 4, 4, 16);
      divider.setRotationPoint(-3F, 14F, -8F);
      divider.setTextureSize(64, 64);
      divider.mirror = true;
      setRotation(divider, 0F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5);
    core.render(f5);
    base.render(f5);
    head1.render(f5);
    head2.render(f5);
    divider.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5);
  }

}
