modLoader="javafml"
loaderVersion="[28,)"
logoFile="lcc.png"
credits="TheGirlinGrey"
authors="joshmanisdabomb"
[[mods]]
	modId="lcc"
	version="a0.5"
	displayName="Loosely Connected Concepts"
	description='''
An assortment of blocks, items, mobs, biomes and dimensions that stand on their own but also connect to each other.
Like a sub-par expansion pack to Minecraft.
'''

[[dependencies.lcc]]
    modId="forge"
    mandatory=true
    versionRange="[28,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.lcc]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.4]"
    ordering="NONE"
    side="BOTH"