modLoader="javafml"
loaderVersion="[25,)"
logoFile="lcc.png"
credits="TheGirlinGrey"
authors="joshmanisdabomb"
[[mods]]
	modId="lcc"
	version="0.1"
	displayName="Loosely Connected Concepts"
	description='''
An assortment of blocks, items, mobs, biomes and dimensions that stand on their own but also connect in some way.
Like a sub-par expansion pack to Minecraft.
'''

[[dependencies.lcc]]
    modId="forge"
    mandatory=true
    versionRange="[25,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.lcc]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.13.2]"
    ordering="NONE"
    side="BOTH"