modLoader="javafml"
loaderVersion="[31,)"
logoFile="lcc.png"
credits="TheGirlinGrey"
authors="joshmanisdabomb"
[[mods]]
	modId="lcc"
	version="b1.0"
	displayName="Loosely Connected Concepts"
	description='''
An assortment of blocks, items, mobs, biomes and dimensions that stand on their own but also connect to each other.
Like a sub-par expansion pack to Minecraft.
'''

[[dependencies.lcc]]
    modId="forge"
    mandatory=true
    versionRange="[31,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.lcc]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"