// Date: 03/6/2014 10:11:34 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX

package yam.entity.model;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;
import net.minecraft.util.MathHelper;

public class ModelLollipopper extends ModelBase
{
	public ModelRenderer head;
	public ModelRenderer body;
	public ModelRenderer rightarm;
	public ModelRenderer leftarm;
	public ModelRenderer rightleg;
	public ModelRenderer leftleg;
  
  public ModelLollipopper()
  {
      textureWidth = 64;
      textureHeight = 64;
    
      head = new ModelRenderer(this, 0, 0);
      head.addBox(-15F, -30F, -1F, 30, 30, 2);
      head.setRotationPoint(0F, 0F, 0F);
      head.setTextureSize(64, 64);
      head.mirror = true;
      setRotation(head, 0F, 0F, 0F);
      body = new ModelRenderer(this, 0, 32);
      body.addBox(-0.5F, 0F, -0.5F, 1, 12, 1);
      body.setRotationPoint(0F, 0F, 0F);
      body.setTextureSize(64, 64);
      body.mirror = true;
      setRotation(body, 0F, 0F, 0F);
      rightarm = new ModelRenderer(this, 0, 32);
      rightarm.addBox(-0.5F, 0F, -0.5F, 1, 12, 1);
      rightarm.setRotationPoint(-1F, 0F, 0F);
      rightarm.setTextureSize(64, 64);
      rightarm.mirror = true;
      setRotation(rightarm, 0F, 0F, 0F);
      leftarm = new ModelRenderer(this, 0, 32);
      leftarm.addBox(-0.5F, 0F, -0.5F, 1, 12, 1);
      leftarm.setRotationPoint(0.5F, 12F, 0F);
      leftarm.setTextureSize(64, 64);
      leftarm.mirror = true;
      setRotation(leftarm, 0F, 0F, 0F);
      rightleg = new ModelRenderer(this, 0, 32);
      rightleg.addBox(-0.5F, 0F, -0.5F, 1, 12, 1);
      rightleg.setRotationPoint(-0.5F, 12F, 0F);
      rightleg.setTextureSize(64, 64);
      rightleg.mirror = true;
      setRotation(rightleg, 0F, 0F, 0F);
      leftleg = new ModelRenderer(this, 0, 32);
      leftleg.addBox(-0.5F, 0F, -0.5F, 1, 12, 1);
      leftleg.setRotationPoint(1F, 0F, 0F);
      leftleg.setTextureSize(64, 64);
      leftleg.mirror = true;
      setRotation(leftleg, 0F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
	  super.render(entity, f, f1, f2, f3, f4, f5);
	  setRotationAngles(f, f1, f2, f3, f4, f5, entity);
	  head.render(f5);
	  body.render(f5);
	  rightarm.render(f5);
	  leftarm.render(f5);
	  rightleg.render(f5);
	  leftleg.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
	  model.rotateAngleX = x;
	  model.rotateAngleY = y;
	  model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity e6)
  {
	  this.head.rotateAngleY = f3 / (180F / (float)Math.PI);
      this.head.rotateAngleX = f4 / (180F / (float)Math.PI);
      this.rightarm.rotateAngleX = MathHelper.cos(f * 0.6662F + (float)Math.PI) * 2.0F * f1 * 0.5F;
      this.leftarm.rotateAngleX = MathHelper.cos(f * 0.6662F) * 2.0F * f1 * 0.5F;
      this.rightarm.rotateAngleZ = 0.0F;
      this.leftarm.rotateAngleZ = 0.0F;
      this.leftleg.rotateAngleX = MathHelper.cos(f * 0.6662F) * 1.4F * f1;
      this.rightleg.rotateAngleX = MathHelper.cos(f * 0.6662F + (float)Math.PI) * 1.4F * f1;
      this.leftleg.rotateAngleY = 0.0F;
      this.rightleg.rotateAngleY = 0.0F;
      
	  //super.setRotationAngles(f, f1, f2, f3, f4, f5, e6);
  }

}
