// Date: 10/01/2016 23:17:52
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package yam.entity.model;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelWingedCreeper extends ModelBase
{
  //fields
    ModelRenderer head;
    ModelRenderer body;
    ModelRenderer leg3;
    ModelRenderer leg4;
    ModelRenderer leg1;
    ModelRenderer leg2;
    ModelRenderer wing1;
    ModelRenderer wing2;
  
  public ModelWingedCreeper()
  {
    textureWidth = 64;
    textureHeight = 64;
    
      head = new ModelRenderer(this, 0, 0);
      head.addBox(-5F, -10F, -5F, 10, 10, 10);
      head.setRotationPoint(0F, 2F, 0F);
      head.setTextureSize(64, 64);
      head.mirror = true;
      setRotation(head, 0F, 0F, 0F);
      body = new ModelRenderer(this, 16, 20);
      body.addBox(-5F, 0F, -3F, 10, 16, 6);
      body.setRotationPoint(0F, 2F, 0F);
      body.setTextureSize(64, 64);
      body.mirror = true;
      setRotation(body, 0F, 0F, 0F);
      leg3 = new ModelRenderer(this, 0, 20);
      leg3.addBox(-2F, 0F, -4F, 4, 6, 4);
      leg3.setRotationPoint(-3F, 18F, -3F);
      leg3.setTextureSize(64, 64);
      leg3.mirror = true;
      setRotation(leg3, 0F, 0F, 0F);
      leg4 = new ModelRenderer(this, 0, 20);
      leg4.addBox(-2F, 0F, -4F, 4, 6, 4);
      leg4.setRotationPoint(3F, 18F, -3F);
      leg4.setTextureSize(64, 64);
      leg4.mirror = true;
      setRotation(leg4, 0F, 0F, 0F);
      leg1 = new ModelRenderer(this, 0, 20);
      leg1.addBox(-2F, 0F, 0F, 4, 6, 4);
      leg1.setRotationPoint(-3F, 18F, 3F);
      leg1.setTextureSize(64, 64);
      leg1.mirror = true;
      setRotation(leg1, 0F, 0F, 0F);
      leg2 = new ModelRenderer(this, 0, 20);
      leg2.addBox(-2F, 0F, 0F, 4, 6, 4);
      leg2.setRotationPoint(3F, 18F, 3F);
      leg2.setTextureSize(64, 64);
      leg2.mirror = true;
      setRotation(leg2, 0F, 0F, 0F);
      wing1 = new ModelRenderer(this, 0, 42);
      wing1.addBox(0F, 0F, 0F, 0, 8, 12);
      wing1.setRotationPoint(0F, 2.2F, 3F);
      wing1.setTextureSize(64, 64);
      wing1.mirror = true;
      setRotation(wing1, 0F, 0F, 0F);
      wing2 = new ModelRenderer(this, 0, 42);
      wing2.addBox(0F, 0F, 0F, 0, 8, 12);
      wing2.setRotationPoint(0F, 2.2F, 3F);
      wing2.setTextureSize(64, 64);
      wing2.mirror = true;
      setRotation(wing2, 0F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    head.render(f5);
    body.render(f5);
    leg3.render(f5);
    leg4.render(f5);
    leg1.render(f5);
    leg2.render(f5);
    wing1.render(f5);
    wing2.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity e)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5, e);
  }

}
