// Date: 16/6/2014 4:53:27 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX
package yam.entity.model;

import java.util.Random;

import yam.entity.EntityRainbot;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelRainbot extends ModelBase
{
	//fields
	ModelRenderer head1;
    ModelRenderer head2;
    ModelRenderer head3;
    ModelRenderer head4;
    ModelRenderer head5;
    ModelRenderer head6;
    ModelRenderer head7;
    ModelRenderer head8;
    ModelRenderer head9;
    ModelRenderer head10;
    ModelRenderer head11;
    ModelRenderer head12;
    ModelRenderer crystal;
    ModelRenderer jaw;
    ModelRenderer jawbone;
    ModelRenderer eyeL;
    ModelRenderer eyeR;
    
	public ModelRainbot()
	{
		textureWidth = 32;
		textureHeight = 32;

		head1 = new ModelRenderer(this, 0, 0);
		head1.addBox(-4F, -4F, -4F, 2, 2, 8);
		head1.setRotationPoint(0F, 12F, 0F);
		head1.setTextureSize(32, 32);
		head1.mirror = true;
		setRotation(head1, 0F, 0F, 0F);
		head2 = new ModelRenderer(this, 0, 0);
		head2.addBox(2F, -4F, -4F, 2, 2, 8);
		head2.setRotationPoint(0F, 12F, 0F);
		head2.setTextureSize(32, 32);
		head2.mirror = true;
		setRotation(head2, 0F, 0F, 0F);
		head3 = new ModelRenderer(this, 0, 0);
		head3.addBox(2F, 2F, -4F, 2, 1, 8);
		head3.setRotationPoint(0F, 12F, 0F);
		head3.setTextureSize(32, 32);
		head3.mirror = true;
		setRotation(head3, 0F, 0F, 0F);
		head4 = new ModelRenderer(this, 0, 0);
		head4.addBox(-4F, 2F, -4F, 2, 1, 8);
		head4.setRotationPoint(0F, 12F, 0F);
		head4.setTextureSize(32, 32);
		head4.mirror = true;
		setRotation(head4, 0F, 0F, 0F);
		head5 = new ModelRenderer(this, 0, 0);
		head5.addBox(-2F, 2F, -4F, 4, 1, 2);
		head5.setRotationPoint(0F, 12F, 0F);
		head5.setTextureSize(32, 32);
		head5.mirror = true;
		setRotation(head5, 0F, 0F, 0F);
		head6 = new ModelRenderer(this, 0, 0);
		head6.addBox(-2F, 2F, 2F, 4, 1, 2);
		head6.setRotationPoint(0F, 12F, 0F);
		head6.setTextureSize(32, 32);
		head6.mirror = true;
		setRotation(head6, 0F, 0F, 0F);
		head7 = new ModelRenderer(this, 0, 0);
		head7.addBox(-2F, -4F, -4F, 4, 2, 2);
		head7.setRotationPoint(0F, 12F, 0F);
		head7.setTextureSize(32, 32);
		head7.mirror = true;
		setRotation(head7, 0F, 0F, 0F);
		head8 = new ModelRenderer(this, 0, 0);
		head8.addBox(-2F, -4F, 2F, 4, 2, 2);
		head8.setRotationPoint(0F, 12F, 0F);
		head8.setTextureSize(32, 32);
		head8.mirror = true;
		setRotation(head8, 0F, 0F, 0F);
		head9 = new ModelRenderer(this, 0, 0);
		head9.addBox(2F, -2F, 2F, 2, 4, 2);
		head9.setRotationPoint(0F, 12F, 0F);
		head9.setTextureSize(32, 32);
		head9.mirror = true;
		setRotation(head9, 0F, 0F, 0F);
		head10 = new ModelRenderer(this, 0, 0);
	      head10.addBox(2F, -2F, -4F, 2, 4, 2);
	      head10.setRotationPoint(0F, 12F, 0F);
	      head10.setTextureSize(32, 32);
	      head10.mirror = true;
	      setRotation(head10, 0F, 0F, 0F);
	      head11 = new ModelRenderer(this, 0, 0);
	      head11.addBox(-4F, -2F, 2F, 2, 4, 2);
	      head11.setRotationPoint(0F, 12F, 0F);
	      head11.setTextureSize(32, 32);
	      head11.mirror = true;
	      setRotation(head11, 0F, 0F, 0F);
	      head12 = new ModelRenderer(this, 0, 0);
	      head12.addBox(-4F, -2F, -4F, 2, 4, 2);
	      head12.setRotationPoint(0F, 12F, 0F);
	      head12.setTextureSize(32, 32);
	      head12.mirror = true;
	      setRotation(head12, 0F, 0F, 0F);
	      crystal = new ModelRenderer(this, 0, 22);
	      crystal.addBox(-1.5F, -1.5F, -1.5F, 3, 3, 3);
	      crystal.setRotationPoint(0F, 12F, 0F);
	      crystal.setTextureSize(32, 32);
	      crystal.mirror = true;
	      setRotation(crystal, 0F, 0F, 0F);
	      jaw = new ModelRenderer(this, 0, 10);
	      jaw.addBox(-4F, 3F, -4F, 8, 2, 8);
	      jaw.setRotationPoint(0F, 12F, 0F);
	      jaw.setTextureSize(32, 32);
	      jaw.mirror = true;
	      setRotation(jaw, 0F, 0F, 0F);
	      jawbone = new ModelRenderer(this, 0, 0);
	      jawbone.addBox(-3F, 3F, 2.9F, 6, 2, 1);
	      jawbone.setRotationPoint(0F, 12F, 0F);
	      jawbone.setTextureSize(32, 32);
	      jawbone.mirror = true;
	      setRotation(jawbone, 0F, 0F, 0F);
	      eyeL = new ModelRenderer(this, 0, 20);
	      eyeL.addBox(2.5F, -3.5F, -5F, 1, 1, 1);
	      eyeL.setRotationPoint(0F, 12F, 0F);
	      eyeL.setTextureSize(32, 32);
	      eyeL.mirror = true;
	      setRotation(eyeL, 0F, 0F, 0F);
	      eyeR = new ModelRenderer(this, 4, 20);
	      eyeR.addBox(-3.5F, -3.5F, -5F, 1, 1, 1);
	      eyeR.setRotationPoint(0F, 12F, 0F);
	      eyeR.setTextureSize(32, 32);
	      eyeR.mirror = true;
	      setRotation(eyeR, 0F, 0F, 0F);
	}

	public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
	{
		super.render(entity, f, f1, f2, f3, f4, f5);
		setRotationAngles(f, f1, f2, f3, f4, f5, entity);
		head1.render(f5);
		head2.render(f5);
		head3.render(f5);
		head4.render(f5);
		head5.render(f5);
		head6.render(f5);
		head7.render(f5);
		head8.render(f5);
		head9.render(f5);
		head10.render(f5);
		head11.render(f5);
		head12.render(f5);
		jaw.render(f5);
	    jawbone.render(f5);
	    eyeL.render(f5);
	    eyeR.render(f5);
	    crystal.render(f5);
	}

	private void setRotation(ModelRenderer model, float x, float y, float z)
	{
		model.rotateAngleX = x;
		model.rotateAngleY = y;
		model.rotateAngleZ = z;
	}

	public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity entity)
	{
		this.newHeadAngle(f3 / (180F / (float)Math.PI), f4 / (180F / (float)Math.PI));
		this.newCrystalAngles(entity);
		this.newJawLocation();

		super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
	}

	private void newJawLocation() {
		Random rand = new Random();
		float min = 3f; float max = 5f;
		
		/*jaw.offsetY = jaw.offsetY + (rand.nextFloat() / 10.0F - 0.05F);
		if (jaw.offsetY > max) {jaw.offsetY = min;}
		else if (jaw.offsetY < min) {jaw.offsetY = max;}*/
	}

	private void newHeadAngle(float f, float g) {
		this.head1.rotateAngleY = f; this.head1.rotateAngleX = g;
		this.head2.rotateAngleY = f; this.head2.rotateAngleX = g;
		this.head3.rotateAngleY = f; this.head3.rotateAngleX = g;
		this.head4.rotateAngleY = f; this.head4.rotateAngleX = g;
		this.head5.rotateAngleY = f; this.head5.rotateAngleX = g;
		this.head6.rotateAngleY = f; this.head6.rotateAngleX = g;
		this.head7.rotateAngleY = f; this.head7.rotateAngleX = g;
		this.head8.rotateAngleY = f; this.head8.rotateAngleX = g;
		this.head9.rotateAngleY = f; this.head9.rotateAngleX = g;
		this.head10.rotateAngleY = f; this.head10.rotateAngleX = g;
		this.head11.rotateAngleY = f; this.head11.rotateAngleX = g;
		this.head12.rotateAngleY = f; this.head12.rotateAngleX = g;
		this.jaw.rotateAngleY = f; this.jaw.rotateAngleX = g;
		this.jawbone.rotateAngleY = f; this.jawbone.rotateAngleX = g;
		this.eyeL.rotateAngleY = f; this.eyeL.rotateAngleX = g;
		this.eyeR.rotateAngleY = f; this.eyeR.rotateAngleX = g;
	}

	private void newCrystalAngles(Entity entity) {
		Random rand = new Random();
		EntityRainbot entity1 = (EntityRainbot)entity;

		crystal.rotateAngleX += entity1.crystalSpeedX;
		crystal.rotateAngleY += entity1.crystalSpeedY;
		crystal.rotateAngleZ += entity1.crystalSpeedZ;
	}

}
