// Date: 5/4/2013 2:30:53 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package yam.entity.model;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelFly extends ModelBase
{
  //fields
    ModelRenderer Body;
    ModelRenderer LeftWing;
    ModelRenderer RightWing;
  
  public ModelFly()
  {
    textureWidth = 6;
    textureHeight = 4;
    
      Body = new ModelRenderer(this, 0, 0);
      Body.addBox(0F, 0F, 0F, 1, 1, 1);
      Body.setRotationPoint(0F, 0F, 0F);
      Body.setTextureSize(6, 4);
      Body.mirror = true;
      setRotation(Body, 0F, 0F, 0F);
      LeftWing = new ModelRenderer(this, 0, 2);
      LeftWing.addBox(0F, 0F, 0F, 2, 0, 1);
      LeftWing.setRotationPoint(1F, 0F, 0F);
      LeftWing.setTextureSize(6, 4);
      LeftWing.mirror = true;
      setRotation(LeftWing, 0F, 0F, 0F);
      RightWing = new ModelRenderer(this, 0, 2);
      RightWing.addBox(0F, 0F, 0F, 2, 0, 1);
      RightWing.setRotationPoint(0F, 0F, 1F);
      RightWing.setTextureSize(6, 4);
      RightWing.mirror = true;
      setRotation(RightWing, 0F, 3.141593F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    Body.render(f5);
    LeftWing.render(f5);
    RightWing.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity e)
  {
	  LeftWing.rotateAngleZ = (float)Math.sin(f2);
	  RightWing.rotateAngleZ = -(float)Math.sin(f2);
	  super.setRotationAngles(f, f1, f2, f3, f4, f5, e);
  }

}
