// Date: 22/2/2015 7:22:43 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package net.minecraft.src;

public class ModelModel extends ModelBase
{
  //fields
    ModelRenderer body;
    ModelRenderer head1;
    ModelRenderer head2;
    ModelRenderer head3;
    ModelRenderer tail1-1;
    ModelRenderer tail1-2;
    ModelRenderer tail1-3;
    ModelRenderer tail2-1;
    ModelRenderer tail2-2;
    ModelRenderer tail2-3;
  
  public ModelModel()
  {
    textureWidth = 32;
    textureHeight = 64;
    
      body = new ModelRenderer(this, 0, 0);
      body.addBox(-4F, -23F, -4F, 8, 20, 8);
      body.setRotationPoint(0F, 24F, 0F);
      body.setTextureSize(32, 64);
      body.mirror = true;
      setRotation(body, 0F, 0F, 0F);
      head1 = new ModelRenderer(this, 0, 28);
      head1.addBox(-3.5F, -3F, -3.5F, 7, 1, 7);
      head1.setRotationPoint(0F, 24F, 0F);
      head1.setTextureSize(32, 64);
      head1.mirror = true;
      setRotation(head1, 0F, 0F, 0F);
      head2 = new ModelRenderer(this, 0, 28);
      head2.addBox(-2.5F, -2F, -2.5F, 5, 1, 5);
      head2.setRotationPoint(0F, 24F, 0F);
      head2.setTextureSize(32, 64);
      head2.mirror = true;
      setRotation(head2, 0F, 0F, 0F);
      head3 = new ModelRenderer(this, 0, 36);
      head3.addBox(-1F, -1F, -1F, 2, 1, 2);
      head3.setRotationPoint(0F, 24F, 0F);
      head3.setTextureSize(32, 64);
      head3.mirror = true;
      setRotation(head3, 0F, 0F, 0F);
      tail1-1 = new ModelRenderer(this, 0, 39);
      tail1-1.addBox(-5F, -19F, -0.5F, 1, 2, 1);
      tail1-1.setRotationPoint(0F, 24F, 0F);
      tail1-1.setTextureSize(32, 64);
      tail1-1.mirror = true;
      setRotation(tail1-1, 0F, 0F, 0F);
      tail1-2 = new ModelRenderer(this, 0, 42);
      tail1-2.addBox(-6F, -21F, -0.5F, 2, 2, 1);
      tail1-2.setRotationPoint(0F, 24F, 0F);
      tail1-2.setTextureSize(32, 64);
      tail1-2.mirror = true;
      setRotation(tail1-2, 0F, 0F, 0F);
      tail1-3 = new ModelRenderer(this, 0, 45);
      tail1-3.addBox(-7F, -23F, -0.5F, 3, 2, 1);
      tail1-3.setRotationPoint(0F, 24F, 0F);
      tail1-3.setTextureSize(32, 64);
      tail1-3.mirror = true;
      setRotation(tail1-3, 0F, 0F, 0F);
      tail2-1 = new ModelRenderer(this, 0, 39);
      tail2-1.addBox(4F, -19F, -0.5F, 1, 2, 1);
      tail2-1.setRotationPoint(0F, 24F, 0F);
      tail2-1.setTextureSize(32, 64);
      tail2-1.mirror = true;
      setRotation(tail2-1, 0F, 0F, 0F);
      tail2-2 = new ModelRenderer(this, 0, 42);
      tail2-2.addBox(4F, -21F, -0.5F, 2, 2, 1);
      tail2-2.setRotationPoint(0F, 24F, 0F);
      tail2-2.setTextureSize(32, 64);
      tail2-2.mirror = true;
      setRotation(tail2-2, 0F, 0F, 0F);
      tail2-3 = new ModelRenderer(this, 0, 45);
      tail2-3.addBox(4F, -23F, -0.5F, 3, 2, 1);
      tail2-3.setRotationPoint(0F, 24F, 0F);
      tail2-3.setTextureSize(32, 64);
      tail2-3.mirror = true;
      setRotation(tail2-3, 0F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5);
    body.render(f5);
    head1.render(f5);
    head2.render(f5);
    head3.render(f5);
    tail1-1.render(f5);
    tail1-2.render(f5);
    tail1-3.render(f5);
    tail2-1.render(f5);
    tail2-2.render(f5);
    tail2-3.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5);
  }

}
