// Date: 15/2/2015 9:14:12 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package yam.entity.model;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;
import net.minecraft.util.MathHelper;

public class ModelTick extends ModelBase
{
  //fields
    ModelRenderer skull;
    ModelRenderer head;
    ModelRenderer thigh1;
    ModelRenderer knee1;
    ModelRenderer leg1;
    ModelRenderer thigh2;
    ModelRenderer knee2;
    ModelRenderer leg2;
    ModelRenderer thigh3;
    ModelRenderer knee3;
    ModelRenderer leg3;
    ModelRenderer thigh4;
    ModelRenderer knee4;
    ModelRenderer leg4;
    ModelRenderer thigh5;
    ModelRenderer knee5;
    ModelRenderer leg5;
    ModelRenderer thigh6;
    ModelRenderer knee6;
    ModelRenderer leg6;
    ModelRenderer eye;
  
  public ModelTick()
  {
    textureWidth = 64;
    textureHeight = 64;
    
      skull = new ModelRenderer(this, 0, 0);
      skull.addBox(-5F, -5F, -5F, 10, 4, 10);
      skull.setRotationPoint(0F, 12F, 0F);
      skull.setTextureSize(64, 64);
      skull.mirror = true;
      setRotation(skull, 0F, 0F, 0F);
      head = new ModelRenderer(this, 0, 14);
      head.addBox(-4.5F, -1F, -4.5F, 9, 6, 9);
      head.setRotationPoint(0F, 12F, 0F);
      head.setTextureSize(64, 64);
      head.mirror = true;
      setRotation(head, 0F, 0F, 0F);
      thigh1 = new ModelRenderer(this, 0, 14);
      thigh1.addBox(0F, -0.5F, -0.5F, 3, 1, 1);
      thigh1.setRotationPoint(4.5F, 14F, -3F);
      thigh1.setTextureSize(64, 64);
      thigh1.mirror = true;
      setRotation(thigh1, 0F, 0F, 0F);
      knee1 = new ModelRenderer(this, 0, 0);
      knee1.addBox(3F, -0.5F, -1F, 2, 3, 2);
      knee1.setRotationPoint(4.5F, 14F, -3F);
      knee1.setTextureSize(64, 64);
      knee1.mirror = true;
      setRotation(knee1, 0F, 0F, 0F);
      leg1 = new ModelRenderer(this, 0, 29);
      leg1.addBox(4F, 2.5F, -0.5F, 1, 8, 1);
      leg1.setRotationPoint(4.5F, 14F, -3F);
      leg1.setTextureSize(64, 64);
      leg1.mirror = true;
      setRotation(leg1, 0F, 0F, 0F);
      thigh2 = new ModelRenderer(this, 0, 14);
      thigh2.addBox(0F, -0.5F, -0.5F, 3, 1, 1);
      thigh2.setRotationPoint(4.5F, 14F, 0F);
      thigh2.setTextureSize(64, 64);
      thigh2.mirror = true;
      setRotation(thigh2, 0F, 0F, 0F);
      knee2 = new ModelRenderer(this, 0, 0);
      knee2.addBox(3F, -0.5F, -1F, 2, 3, 2);
      knee2.setRotationPoint(4.5F, 14F, 0F);
      knee2.setTextureSize(64, 64);
      knee2.mirror = true;
      setRotation(knee2, 0F, 0F, 0F);
      leg2 = new ModelRenderer(this, 0, 29);
      leg2.addBox(4F, 2.5F, -0.5F, 1, 8, 1);
      leg2.setRotationPoint(4.5F, 14F, 0F);
      leg2.setTextureSize(64, 64);
      leg2.mirror = true;
      setRotation(leg2, 0F, 0F, 0F);
      thigh3 = new ModelRenderer(this, 0, 14);
      thigh3.addBox(0F, -0.5F, -0.5F, 3, 1, 1);
      thigh3.setRotationPoint(4.5F, 14F, 3F);
      thigh3.setTextureSize(64, 64);
      thigh3.mirror = true;
      setRotation(thigh3, 0F, 0F, 0F);
      knee3 = new ModelRenderer(this, 0, 0);
      knee3.addBox(3F, -0.5F, -1F, 2, 3, 2);
      knee3.setRotationPoint(4.5F, 14F, 3F);
      knee3.setTextureSize(64, 64);
      knee3.mirror = true;
      setRotation(knee3, 0F, 0F, 0F);
      leg3 = new ModelRenderer(this, 0, 29);
      leg3.addBox(4F, 2.5F, -0.5F, 1, 8, 1);
      leg3.setRotationPoint(4.5F, 14F, 3F);
      leg3.setTextureSize(64, 64);
      leg3.mirror = true;
      setRotation(leg3, 0F, 0F, 0F);
      thigh4 = new ModelRenderer(this, 0, 14);
      thigh4.addBox(-3F, -0.5F, -0.5F, 3, 1, 1);
      thigh4.setRotationPoint(-4.5F, 14F, -3F);
      thigh4.setTextureSize(64, 64);
      thigh4.mirror = true;
      setRotation(thigh4, 0F, 0F, 0F);
      knee4 = new ModelRenderer(this, 0, 0);
      knee4.addBox(-5F, -0.5F, -1F, 2, 3, 2);
      knee4.setRotationPoint(-4.5F, 14F, -3F);
      knee4.setTextureSize(64, 64);
      knee4.mirror = true;
      setRotation(knee4, 0F, 0F, 0F);
      leg4 = new ModelRenderer(this, 0, 29);
      leg4.addBox(-5F, 2.5F, -0.5F, 1, 8, 1);
      leg4.setRotationPoint(-4.5F, 14F, -3F);
      leg4.setTextureSize(64, 64);
      leg4.mirror = true;
      setRotation(leg4, 0F, 0F, 0F);
      thigh5 = new ModelRenderer(this, 0, 14);
      thigh5.addBox(-3F, -0.5F, -0.5F, 3, 1, 1);
      thigh5.setRotationPoint(-4.5F, 14F, 0F);
      thigh5.setTextureSize(64, 64);
      thigh5.mirror = true;
      setRotation(thigh5, 0F, 0F, 0F);
      knee5 = new ModelRenderer(this, 0, 0);
      knee5.addBox(-5F, -0.5F, -1F, 2, 3, 2);
      knee5.setRotationPoint(-4.5F, 14F, 0F);
      knee5.setTextureSize(64, 64);
      knee5.mirror = true;
      setRotation(knee5, 0F, 0F, 0F);
      leg5 = new ModelRenderer(this, 0, 29);
      leg5.addBox(-5F, 2.5F, -0.5F, 1, 8, 1);
      leg5.setRotationPoint(-4.5F, 14F, 0F);
      leg5.setTextureSize(64, 64);
      leg5.mirror = true;
      setRotation(leg5, 0F, 0F, 0F);
      thigh6 = new ModelRenderer(this, 0, 14);
      thigh6.addBox(-3F, -0.5F, -0.5F, 3, 1, 1);
      thigh6.setRotationPoint(-4.5F, 14F, 3F);
      thigh6.setTextureSize(64, 64);
      thigh6.mirror = true;
      setRotation(thigh6, 0F, 0F, 0F);
      knee6 = new ModelRenderer(this, 0, 0);
      knee6.addBox(-5F, -0.5F, -1F, 2, 3, 2);
      knee6.setRotationPoint(-4.5F, 14F, 3F);
      knee6.setTextureSize(64, 64);
      knee6.mirror = true;
      setRotation(knee6, 0F, 0F, 0F);
      leg6 = new ModelRenderer(this, 0, 29);
      leg6.addBox(-5F, 2.5F, -0.5F, 1, 8, 1);
      leg6.setRotationPoint(-4.5F, 14F, 3F);
      leg6.setTextureSize(64, 64);
      leg6.mirror = true;
      setRotation(leg6, 0F, 0F, 0F);
      eye = new ModelRenderer(this, 0, 38);
      eye.addBox(-2F, -2F, -2F, 4, 4, 4);
      eye.setRotationPoint(0F, 5F, 0F);
      eye.setTextureSize(64, 64);
      eye.mirror = true;
      setRotation(eye, 0F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    skull.render(f5);
    head.render(f5);
    thigh1.render(f5);
    knee1.render(f5);
    leg1.render(f5);
    thigh2.render(f5);
    knee2.render(f5);
    leg2.render(f5);
    thigh3.render(f5);
    knee3.render(f5);
    leg3.render(f5);
    thigh4.render(f5);
    knee4.render(f5);
    leg4.render(f5);
    thigh5.render(f5);
    knee5.render(f5);
    leg5.render(f5);
    thigh6.render(f5);
    knee6.render(f5);
    leg6.render(f5);
    eye.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity e)
  {
	  this.eye.rotateAngleY = f3 / (180F / (float)Math.PI);
      this.eye.rotateAngleX = f4 / (180F / (float)Math.PI);
      float f6 = ((float)Math.PI / 4F);
      this.leg1.rotateAngleZ = -f6;
      this.leg2.rotateAngleZ = f6;
      this.leg3.rotateAngleZ = -f6 * 0.74F;
      this.leg4.rotateAngleZ = f6 * 0.74F;
      this.leg5.rotateAngleZ = -f6 * 0.74F;
      this.leg6.rotateAngleZ = f6 * 0.74F;
      float f7 = -0.0F;
      float f8 = 0.3926991F;
      this.leg1.rotateAngleY = f8 * 2.0F + f7;
      this.leg2.rotateAngleY = -f8 * 2.0F - f7;
      this.leg3.rotateAngleY = f8 * 1.0F + f7;
      this.leg4.rotateAngleY = -f8 * 1.0F - f7;
      this.leg5.rotateAngleY = -f8 * 1.0F + f7;
      this.leg6.rotateAngleY = f8 * 1.0F - f7;
      float f9 = -(MathHelper.cos(f * 0.6662F * 2.0F + 0.0F) * 0.4F) * f1;
      float f10 = -(MathHelper.cos(f * 0.6662F * 2.0F + (float)Math.PI) * 0.4F) * f1;
      float f11 = -(MathHelper.cos(f * 0.6662F * 2.0F + ((float)Math.PI / 2F)) * 0.4F) * f1;
      float f13 = Math.abs(MathHelper.sin(f * 0.6662F + 0.0F) * 0.4F) * f1;
      float f14 = Math.abs(MathHelper.sin(f * 0.6662F + (float)Math.PI) * 0.4F) * f1;
      float f15 = Math.abs(MathHelper.sin(f * 0.6662F + ((float)Math.PI / 2F)) * 0.4F) * f1;
      this.leg1.rotateAngleY += f9;
      this.leg2.rotateAngleY += -f9;
      this.leg3.rotateAngleY += f10;
      this.leg4.rotateAngleY += -f10;
      this.leg5.rotateAngleY += f11;
      this.leg6.rotateAngleY += -f11;
      this.leg1.rotateAngleZ += f13;
      this.leg2.rotateAngleZ += -f13;
      this.leg3.rotateAngleZ += f14;
      this.leg4.rotateAngleZ += -f14;
      this.leg5.rotateAngleZ += f15;
      this.leg6.rotateAngleZ += -f15;
      this.thigh1.rotateAngleX = this.knee1.rotateAngleX = this.leg1.rotateAngleX;
      this.thigh1.rotateAngleY = this.knee1.rotateAngleY = this.leg1.rotateAngleY;
      this.thigh1.rotateAngleZ = this.knee1.rotateAngleZ = this.leg1.rotateAngleZ;
      this.thigh2.rotateAngleX = this.knee2.rotateAngleX = this.leg2.rotateAngleX;
      this.thigh2.rotateAngleY = this.knee2.rotateAngleY = this.leg2.rotateAngleY;
      this.thigh2.rotateAngleZ = this.knee2.rotateAngleZ = this.leg2.rotateAngleZ;
      this.thigh3.rotateAngleX = this.knee3.rotateAngleX = this.leg3.rotateAngleX;
      this.thigh3.rotateAngleY = this.knee3.rotateAngleY = this.leg3.rotateAngleY;
      this.thigh3.rotateAngleZ = this.knee3.rotateAngleZ = this.leg3.rotateAngleZ;
      this.thigh4.rotateAngleX = this.knee4.rotateAngleX = this.leg4.rotateAngleX;
      this.thigh4.rotateAngleY = this.knee4.rotateAngleY = this.leg4.rotateAngleY;
      this.thigh4.rotateAngleZ = this.knee4.rotateAngleZ = this.leg4.rotateAngleZ;
      this.thigh5.rotateAngleX = this.knee5.rotateAngleX = this.leg5.rotateAngleX;
      this.thigh5.rotateAngleY = this.knee5.rotateAngleY = this.leg5.rotateAngleY;
      this.thigh5.rotateAngleZ = this.knee5.rotateAngleZ = this.leg5.rotateAngleZ;
      this.thigh6.rotateAngleX = this.knee6.rotateAngleX = this.leg6.rotateAngleX;
      this.thigh6.rotateAngleY = this.knee6.rotateAngleY = this.leg6.rotateAngleY;
      this.thigh6.rotateAngleZ = this.knee6.rotateAngleZ = this.leg6.rotateAngleZ;
      super.setRotationAngles(f, f1, f2, f3, f4, f5, e);
  }

}
