// Date: 29/10/2014 16:06:07
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package yam.entity.model;

import java.util.Random;

import yam.entity.EntityDerekJr;
import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelDerekJr extends ModelBase
{
  //fields
    ModelRenderer head;
    ModelRenderer body;
    ModelRenderer leg3;
    ModelRenderer leg4;
    ModelRenderer leg1;
    ModelRenderer leg2;
    ModelRenderer cord;
    ModelRenderer head2;
    
    Random r = new Random();
  
  public ModelDerekJr()
  {
    textureWidth = 64;
    textureHeight = 64;
    
      head = new ModelRenderer(this, 0, 0);
      head.addBox(-7F, -11F, -6F, 12, 12, 12);
      head.setRotationPoint(0F, 6F, 0F);
      head.setTextureSize(64, 64);
      head.mirror = true;
      setRotation(head, -0.4833219F, -0.5205006F, -0.6123111F);
      body = new ModelRenderer(this, 0, 28);
      body.addBox(-2F, 0F, -2F, 4, 17, 4);
      body.setRotationPoint(0F, 6F, 0F);
      body.setTextureSize(64, 64);
      body.mirror = true;
      setRotation(body, 0F, 0F, 0F);
      leg3 = new ModelRenderer(this, 24, 24);
      leg3.addBox(-8F, 0F, -4F, 8, 1, 4);
      leg3.setRotationPoint(0F, 23F, 0F);
      leg3.setTextureSize(64, 64);
      leg3.mirror = true;
      setRotation(leg3, 0F, 0F, 0F);
      leg4 = new ModelRenderer(this, 24, 29);
      leg4.addBox(0F, 0F, -8F, 4, 1, 8);
      leg4.setRotationPoint(0F, 23F, 0F);
      leg4.setTextureSize(64, 64);
      leg4.mirror = true;
      setRotation(leg4, 0F, 0F, 0F);
      leg1 = new ModelRenderer(this, 24, 29);
      leg1.addBox(-4F, 0F, 0F, 4, 1, 8);
      leg1.setRotationPoint(0F, 23F, 0F);
      leg1.setTextureSize(64, 64);
      leg1.mirror = true;
      setRotation(leg1, 0F, 0F, 0F);
      leg2 = new ModelRenderer(this, 24, 24);
      leg2.addBox(0F, 0F, 0F, 8, 1, 4);
      leg2.setRotationPoint(0F, 23F, 0F);
      leg2.setTextureSize(64, 64);
      leg2.mirror = true;
      setRotation(leg2, 0F, 0F, 0F);
      cord = new ModelRenderer(this, 0, 24);
      cord.addBox(0F, 0F, 0F, 10, 2, 2);
      cord.setRotationPoint(0F, 7F, -1F);
      cord.setTextureSize(64, 64);
      cord.mirror = true;
      setRotation(cord, 0.1858931F, -0.1858931F, -0.4089647F);
      head2 = new ModelRenderer(this, 24, 38);
      head2.addBox(-3F, -3F, -3F, 6, 6, 6);
      head2.setRotationPoint(8F, 3F, 3F);
      head2.setTextureSize(64, 64);
      head2.mirror = true;
      setRotation(head2, -0.2602503F, 0F, 0.2230717F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    head.render(f5);
    body.render(f5);
    leg3.render(f5);
    leg4.render(f5);
    leg1.render(f5);
    leg2.render(f5);
    cord.render(f5);
    head2.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity e)
  {
	  this.head.rotateAngleY = f3 / (180F / (float)Math.PI);
      this.head.rotateAngleX = f4 / (180F / (float)Math.PI);
      this.head2.rotateAngleY = (f / 2F) + ((EntityDerekJr)e).secondHeadRotation;
      //this.head2.rotateAngleY = f2 + ((EntityDerekJr)e).secondHeadRotation;
	  //this.head2.rotateAngleZ = (float)Math.sin(f2) / 10F;
      leg1.rotateAngleY = f;
	  leg2.rotateAngleY = f;
	  leg3.rotateAngleY = f;
	  leg4.rotateAngleY = f;
	  super.setRotationAngles(f, f1, f2, f3, f4, f5, e);
  }

}
