// Date: 29/10/2014 16:08:46
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package yam.entity.model;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;
import net.minecraft.util.MathHelper;

public class ModelDerek extends ModelBase
{
  //fields
    ModelRenderer head;
    ModelRenderer body;
    ModelRenderer leg3;
    ModelRenderer leg4;
    ModelRenderer leg1;
    ModelRenderer leg2;
    ModelRenderer head2;
    ModelRenderer head3;
    ModelRenderer head4;
  
  public ModelDerek()
  {
    textureWidth = 96;
    textureHeight = 96;
    
      head = new ModelRenderer(this, 0, 0);
      head.addBox(-10F, -15F, -9F, 16, 16, 16);
      head.setRotationPoint(0F, 6F, 0F);
      head.setTextureSize(96, 96);
      head.mirror = true;
      setRotation(head, 0F, 0.0371786F, -0.0743572F);
      body = new ModelRenderer(this, 0, 52);
      body.addBox(-11F, 0F, -11F, 22, 12, 22);
      body.setRotationPoint(0F, 6F, 0F);
      body.setTextureSize(96, 96);
      body.mirror = true;
      setRotation(body, 0F, 0F, 0F);
      leg3 = new ModelRenderer(this, 0, 86);
      leg3.addBox(-4F, 0F, -4F, 4, 6, 4);
      leg3.setRotationPoint(0F, 18F, 0F);
      leg3.setTextureSize(96, 96);
      leg3.mirror = true;
      setRotation(leg3, 0F, 0F, 0F);
      leg4 = new ModelRenderer(this, 0, 86);
      leg4.addBox(-1F, 0F, -4F, 4, 6, 4);
      leg4.setRotationPoint(1F, 18F, 0F);
      leg4.setTextureSize(96, 96);
      leg4.mirror = true;
      setRotation(leg4, 0F, 0F, 0F);
      leg1 = new ModelRenderer(this, 0, 86);
      leg1.addBox(-4F, 0F, 0F, 4, 6, 4);
      leg1.setRotationPoint(0F, 18F, 0F);
      leg1.setTextureSize(96, 96);
      leg1.mirror = true;
      setRotation(leg1, 0F, 0F, 0F);
      leg2 = new ModelRenderer(this, 0, 86);
      leg2.addBox(0F, 0F, 0F, 4, 6, 4);
      leg2.setRotationPoint(0F, 18F, 0F);
      leg2.setTextureSize(96, 96);
      leg2.mirror = true;
      setRotation(leg2, 0F, 0F, 0F);
      head2 = new ModelRenderer(this, 0, 32);
      head2.addBox(0F, 0F, -11F, 10, 10, 10);
      head2.setRotationPoint(0F, 0F, 0F);
      head2.setTextureSize(96, 96);
      head2.mirror = true;
      setRotation(head2, -0.1858931F, -0.0743572F, 0.2602503F);
      head3 = new ModelRenderer(this, 40, 32);
      head3.addBox(3.5F, -8F, -6F, 6, 6, 6);
      head3.setRotationPoint(0F, 0F, 0F);
      head3.setTextureSize(96, 96);
      head3.mirror = true;
      setRotation(head3, 0.0743572F, 0.1115358F, 0.2230717F);
      head4 = new ModelRenderer(this, 0, 32);
      head4.addBox(-10F, -3F, -12F, 10, 10, 10);
      head4.setRotationPoint(0F, 0F, 0F);
      head4.setTextureSize(96, 96);
      head4.mirror = true;
      setRotation(head4, -0.0743572F, 3.141593F, -0.1115358F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    head.render(f5);
    body.render(f5);
    leg3.render(f5);
    leg4.render(f5);
    leg1.render(f5);
    leg2.render(f5);
    head2.render(f5);
    head3.render(f5);
    head4.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity e)
  {
	  this.head.rotateAngleY = f3 / (180F / (float)Math.PI);
      this.head.rotateAngleX = f4 / (180F / (float)Math.PI);
      this.head2.rotateAngleY = (f / 2F);
      this.head3.rotateAngleY = (f2 / 2F);
      this.head4.rotateAngleY = f3 / (180F / (float)Math.PI);
      this.leg1.rotateAngleX = MathHelper.cos(f * 0.6662F) * 1.4F * f1;
      this.leg2.rotateAngleX = MathHelper.cos(f * 0.6662F + (float)Math.PI) * 1.4F * f1;
      this.leg1.rotateAngleY = 0.0F;
      this.leg2.rotateAngleY = 0.0F;
      this.leg4.rotateAngleX = MathHelper.cos(f * 0.6662F) * 1.4F * f1;
      this.leg3.rotateAngleX = MathHelper.cos(f * 0.6662F + (float)Math.PI) * 1.4F * f1;
      this.leg4.rotateAngleY = 0.0F;
      this.leg3.rotateAngleY = 0.0F;
      super.setRotationAngles(f, f1, f2, f3, f4, f5, e);
  }

}
