// Date: 21/12/2015 5:57:41 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package yam.entity.model;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;
import net.minecraft.util.MathHelper;

public class ModelHiddenReptile extends ModelBase
{
  //fields
    ModelRenderer mudtop;
    ModelRenderer mudbottom;
    ModelRenderer head;
    ModelRenderer leg1;
    ModelRenderer leg2;
    ModelRenderer leg3;
    ModelRenderer leg4;
    ModelRenderer leg5;
    ModelRenderer leg6;
  
  public ModelHiddenReptile()
  {
    textureWidth = 64;
    textureHeight = 64;
    
      mudtop = new ModelRenderer(this, 0, 0);
      mudtop.addBox(-8F, -8F, -8F, 16, 10, 16);
      mudtop.setRotationPoint(0F, 9F, 0F);
      mudtop.setTextureSize(64, 64);
      mudtop.mirror = true;
      setRotation(mudtop, 0F, 0F, 0F);
      mudbottom = new ModelRenderer(this, 0, 26);
      mudbottom.addBox(-8F, -8F, -8F, 16, 6, 16);
      mudbottom.setRotationPoint(0F, 25F, 0F);
      mudbottom.setTextureSize(64, 64);
      mudbottom.mirror = true;
      setRotation(mudbottom, 0F, 0F, 0F);
      head = new ModelRenderer(this, 0, 48);
      head.addBox(-3F, -3F, -3F, 6, 6, 6);
      head.setRotationPoint(0F, 14F, 0F);
      head.setTextureSize(64, 64);
      head.mirror = true;
      setRotation(head, 0F, 0F, 0F);
      leg1 = new ModelRenderer(this, 24, 48);
      leg1.addBox(-0.5F, 0F, -0.5F, 1, 1, 1);
      leg1.setRotationPoint(4F, 23F, 3F);
      leg1.setTextureSize(64, 64);
      leg1.mirror = true;
      setRotation(leg1, 0F, 0F, 0F);
      leg2 = new ModelRenderer(this, 24, 48);
      leg2.addBox(-0.5F, 0F, -0.5F, 1, 1, 1);
      leg2.setRotationPoint(-4F, 23F, 3F);
      leg2.setTextureSize(64, 64);
      leg2.mirror = true;
      setRotation(leg2, 0F, 0F, 0F);
      leg3 = new ModelRenderer(this, 24, 48);
      leg3.addBox(-0.5F, 0F, -0.5F, 1, 1, 1);
      leg3.setRotationPoint(4F, 23F, 0F);
      leg3.setTextureSize(64, 64);
      leg3.mirror = true;
      setRotation(leg3, 0F, 0F, 0F);
      leg4 = new ModelRenderer(this, 24, 48);
      leg4.addBox(-0.5F, 0F, -0.5F, 1, 1, 1);
      leg4.setRotationPoint(-4F, 23F, 0F);
      leg4.setTextureSize(64, 64);
      leg4.mirror = true;
      setRotation(leg4, 0F, 0F, 0F);
      leg5 = new ModelRenderer(this, 24, 48);
      leg5.addBox(-0.5F, 0F, -0.5F, 1, 1, 1);
      leg5.setRotationPoint(4F, 23F, -3F);
      leg5.setTextureSize(64, 64);
      leg5.mirror = true;
      setRotation(leg5, 0F, 0F, 0F);
      leg6 = new ModelRenderer(this, 24, 48);
      leg6.addBox(-0.5F, 0F, -0.5F, 1, 1, 1);
      leg6.setRotationPoint(-4F, 23F, -3F);
      leg6.setTextureSize(64, 64);
      leg6.mirror = true;
      setRotation(leg6, 0F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    mudtop.render(f5);
    mudbottom.render(f5);
    head.render(f5);
    leg1.render(f5);
    leg2.render(f5);
    leg3.render(f5);
    leg4.render(f5);
    leg5.render(f5);
    leg6.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity e)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5, e);
    mudtop.rotationPointY = 9F + (MathHelper.sin(1.0F-e.getDataWatcher().getWatchableObjectFloat(16)) * 8.5F);
    mudbottom.rotationPointY = 25F + (MathHelper.sin(1.0F-e.getDataWatcher().getWatchableObjectFloat(16)) * 1.25F);
    head.rotationPointY = 14F + (MathHelper.sin(1.0F-e.getDataWatcher().getWatchableObjectFloat(16)) * 1.25F);
    leg1.rotateAngleX = MathHelper.sin(f3);
    leg2.rotateAngleX = MathHelper.sin(f3 + 1);
    leg3.rotateAngleX = MathHelper.sin(f3 + 2);
    leg4.rotateAngleX = MathHelper.sin(f3 + 3);
    leg5.rotateAngleX = MathHelper.sin(f3 + 4);
    leg6.rotateAngleX = MathHelper.sin(f3 + 5);
  }

}
