// Date: 22/2/2015 7:06:39 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package yam.entity.model;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelMissile extends ModelBase
{
  //fields
    ModelRenderer body;
    ModelRenderer tail1_1;
    ModelRenderer tail1_2;
    ModelRenderer tail2_1;
    ModelRenderer tail2_2;
    ModelRenderer tail3_1;
    ModelRenderer tail3_2;
    ModelRenderer tail4_1;
    ModelRenderer tail4_2;
  
  public ModelMissile()
  {
    textureWidth = 32;
    textureHeight = 32;
    
      body = new ModelRenderer(this, 0, 0);
      body.addBox(-2F, -14F, -2F, 4, 14, 4);
      body.setRotationPoint(0F, 24F, 0F);
      body.setTextureSize(32, 32);
      body.mirror = true;
      setRotation(body, 0F, 0F, 0F);
      tail1_1 = new ModelRenderer(this, 0, 18);
      tail1_1.addBox(1F, -16F, 1F, 2, 2, 2);
      tail1_1.setRotationPoint(0F, 24F, 0F);
      tail1_1.setTextureSize(32, 32);
      tail1_1.mirror = true;
      setRotation(tail1_1, 0F, 0F, 0F);
      tail1_2 = new ModelRenderer(this, 0, 22);
      tail1_2.addBox(2F, -18F, 2F, 1, 2, 1);
      tail1_2.setRotationPoint(0F, 24F, 0F);
      tail1_2.setTextureSize(32, 32);
      tail1_2.mirror = true;
      setRotation(tail1_2, 0F, 0F, 0F);
      tail2_1 = new ModelRenderer(this, 0, 18);
      tail2_1.addBox(-3F, -16F, 1F, 2, 2, 2);
      tail2_1.setRotationPoint(0F, 24F, 0F);
      tail2_1.setTextureSize(32, 32);
      tail2_1.mirror = true;
      setRotation(tail2_1, 0F, 0F, 0F);
      tail2_2 = new ModelRenderer(this, 0, 22);
      tail2_2.addBox(-3F, -18F, 2F, 1, 2, 1);
      tail2_2.setRotationPoint(0F, 24F, 0F);
      tail2_2.setTextureSize(32, 32);
      tail2_2.mirror = true;
      setRotation(tail2_2, 0F, 0F, 0F);
      tail3_1 = new ModelRenderer(this, 0, 18);
      tail3_1.addBox(1F, -16F, -3F, 2, 2, 2);
      tail3_1.setRotationPoint(0F, 24F, 0F);
      tail3_1.setTextureSize(32, 32);
      tail3_1.mirror = true;
      setRotation(tail3_1, 0F, 0F, 0F);
      tail3_2 = new ModelRenderer(this, 0, 22);
      tail3_2.addBox(2F, -18F, -3F, 1, 2, 1);
      tail3_2.setRotationPoint(0F, 24F, 0F);
      tail3_2.setTextureSize(32, 32);
      tail3_2.mirror = true;
      setRotation(tail3_2, 0F, 0F, 0F);
      tail4_1 = new ModelRenderer(this, 0, 18);
      tail4_1.addBox(-3F, -16F, -3F, 2, 2, 2);
      tail4_1.setRotationPoint(0F, 24F, 0F);
      tail4_1.setTextureSize(32, 32);
      tail4_1.mirror = true;
      setRotation(tail4_1, 0F, 0F, 0F);
      tail4_2 = new ModelRenderer(this, 0, 22);
      tail4_2.addBox(-3F, -18F, -3F, 1, 2, 1);
      tail4_2.setRotationPoint(0F, 24F, 0F);
      tail4_2.setTextureSize(32, 32);
      tail4_2.mirror = true;
      setRotation(tail4_2, 0F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    body.render(f5);
    tail1_1.render(f5);
    tail1_2.render(f5);
    tail2_1.render(f5);
    tail2_2.render(f5);
    tail3_1.render(f5);
    tail3_2.render(f5);
    tail4_1.render(f5);
    tail4_2.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity e)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5, e);
  }

}
