name: Build Mod

on:
  push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b
        
      - name: Executify Gradle
        run: chmod +x ./gradlew
                
      - name: Decrease JVM Memory Usage
        run: sed '2 s/.*/org.gradle.jvmargs=-Xms1G -Xmx3G/' gradle.properties > gradle.properties.ci
                
      - name: Commit Gradle Property Changes
        run: cp gradle.properties.ci gradle.properties
                
      - name: Decrease Kotlin Memory Usage
        run: sed '3 s/.*/kotlin.daemon.jvm.options=-Xms1G -Xmx2G/' gradle.properties > gradle.properties.ci
                
      - name: Commit Gradle Property Changes
        run: cp gradle.properties.ci gradle.properties
        
      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2.3.0
        with:
          arguments: build
                
      - name: Rename Source Jar
        run: mv build/devlibs/LooselyConnectedConcepts-*-*-sources.jar build/libs/sources.jar
                
      - name: Rename Build Jar
        run: mv build/libs/LooselyConnectedConcepts-*-*.jar build/libs/build.jar
        
      - name: Deploy Built Jars
        uses: fjogeleit/http-request-action@v1
        with:
          url: ${{ secrets.BUILD_UPLOAD_ENDPOINT }}
          method: 'POST'
          data: '{"key": "${{ secrets.BUILD_UPLOAD_KEY }}", "run_id": "${{ github.run_id }}", "run_number": "${{ github.run_number }}", "ref": "${{ github.ref }}", "ref_name": "${{ github.ref_name }}", "sha": "${{ github.sha }}"}'
          files: '{"build": "${{ github.workspace }}/build/libs/build.jar", "sources": "${{ github.workspace }}/build/libs/sources.jar", "gradle": "${{ github.workspace }}/gradle.properties"}'
